version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout

      # build & tag the application images
      - run: make tag-slim
      - run: make tag-node

      # list images to see what the result was
      - run: docker images

  publish:
    machine: true
    steps:
      # login to docker hub with credentials stored in the UI
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # deploy the images
      - run: echo "in the future, do an actual publish"
      - run: docker images
      #- run: make publish

# set up custom workflow to enable build to run on release tag pushes as well
# https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
workflows:
  version: 2
  build-and-maybe-publish:
    jobs:
      # build on all branch pushes or tags.
      - build:
          filters:
            tags:
              only: /.*/
      # publish on any pushes *to master*, OR any tag pushes if tag begins "v".
      # NOTE: be careful, this means a version tag push to a different branch
      # will also result in publish happening!
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
            tags:
              only: /^v.*/
